### ISSUE TITLE
[Feature] Crate.Click_Actions  CRATE_OPEN_ALL

### ISSUE THREAD

**Issue by Beanzilla** [nulli0n/ExcellentCrates-spigot#104]
My config currently is:

```yaml
Crate:
  Click_Actions:
    LEFT: CRATE_PREVIEW
    RIGHT: CRATE_OPEN
    SHIFT_LEFT: null
    SHIFT_RIGHT: null
```

What I'd like:

```yaml
Crate:
  Click_Actions:
    LEFT: CRATE_PREVIEW
    RIGHT: CRATE_OPEN
    SHIFT_LEFT: null
    SHIFT_RIGHT: CRATE_OPEN_ALL
```

So on Shift Right you'd obtain all the rewards for all the keys you had in your inventory for that chest (like some servers do).

> I'd make it so it would only play 1 of the animations (probably the last rewards animation) if animations are set for that crate.
